#!/bin/bash

set -euo pipefail
IFS=$'\n\t'


usage() {
  grep '^#/' "$0" | cut -c4-;
  exit 0;
}
expr '$*' : ".*--help" > /dev/null && usage

readonly LOG_FILE="/tmp/$(basename "$0").log"
info ()	{ echo "[INFO]	$@" | tee -a "$LOG_FILE" >&2 ; }
warn()	{ echo "[WARN]	$@" | tee -a "$LOG_FILE" >&2 ; }
error()	{ echo "[ERROR]	$@" | tee -a "$LOG_FILE" >&2 ; }
fatal()	{ echo "[FATAL]	$@" | tee -a "$LOG_FILE" >&2 ; exit 1 ; }

cleanup() {
  echo "Cleaning up resources ..."
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  trap cleanup EXIT
  # script goes here
fi
